// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// import 'firebase_options.dart';
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
//  await Firebase.initializeApp(
//    options = DefaultFirebaseOptions.currentPlatform,
//  );

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB3V1gbDndmsMAa3Gp0JRntTGuOXmd1SNg',
    appId: '1:512075256827:web:317c2171e8c266dc58f15e',
    messagingSenderId: '512075256827',
    projectId: 'school-van-track',
    authDomain: 'school-van-track.firebaseapp.com',
    storageBucket: 'school-van-track.firebasestorage.app',
    measurementId: 'G-S4RGJY033B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOpnEYqhiIlbSUoi-5yBbqzbeaX5JNO-k',
    appId: '1:512075256827:android:0943eb3d5397ca6d58f15e',
    messagingSenderId: '512075256827',
    projectId: 'school-van-track',
    storageBucket: 'school-van-track.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBcXaYeSbI9edMGm-GksQm2ivK43pRKUmQ',
    appId: '1:512075256827:ios:5e1ca57d4ceb9e7a58f15e',
    messagingSenderId: '512075256827',
    projectId: 'school-van-track',
    storageBucket: 'school-van-track.firebasestorage.app',
    iosBundleId: 'com.example.schoolVanTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBcXaYeSbI9edMGm-GksQm2ivK43pRKUmQ',
    appId: '1:512075256827:ios:5e1ca57d4ceb9e7a58f15e',
    messagingSenderId: '512075256827',
    projectId: 'school-van-track',
    storageBucket: 'school-van-track.firebasestorage.app',
    iosBundleId: 'com.example.schoolVanTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB3V1gbDndmsMAa3Gp0JRntTGuOXmd1SNg',
    appId: '1:512075256827:web:bcf686ccfbbfb55f58f15e',
    messagingSenderId: '512075256827',
    projectId: 'school-van-track',
    authDomain: 'school-van-track.firebaseapp.com',
    storageBucket: 'school-van-track.firebasestorage.app',
    measurementId: 'G-HHB0H0TN8V',
  );
}
