name: school_van_tracker
description: A school van and children tracking solution for parents.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  # shared_preferences: ^2.2.2
  # http: ^1.1.0
  


  # ✅ Maps & Location
  google_maps_flutter: ^2.5.0
  geolocator: ^10.1.0

  # ✅ State Management & Utilities
  provider: ^6.0.5
  shared_preferences: ^2.2.2
  http: ^1.1.0
  intl: ^0.18.1
  flutter_dotenv: ^5.1.0

  # ✅ UI & UX Enhancements
  flutter_svg: ^2.0.7
  fluttertoast: ^8.2.12
  cached_network_image: ^3.3.0
  url_launcher: ^6.1.14
  # vibration: ^1.7.6

  # ✅ Media & QR
  image_picker: ^1.0.4
  mobile_scanner: ^3.5.2  # ✅ replaces buggy qr_code_scanner
  pretty_qr_code: ^3.0.0
  firebase_core: ^3.13.0
  cloud_firestore: ^5.6.6
  flutter_launcher_icons: ^0.14.3
  firebase_database: ^11.3.5

  # ❌ COMMENTED OUT problematic plugin for now
  # flutter_local_notifications: ^13.0.0
  # qr_code_scanner: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    # - .env
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
